=== api-evangelist/amazon-managed-blockchain/json-schema/amazon-managed-blockchain-proposal-summary-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-managed-blockchain/refs/heads/main/json-schema/amazon-managed-blockchain-proposal-summary-schema.json",
  "title": "ProposalSummary",
  "description": "<p>Properties of a proposal.</p> <p>Applies only to Hyperledger Fabric.</p>",
  "type": "object",
  "properties": {
    "ProposalId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ResourceIdString"
        },
        {
          "description": " The unique identifier of the proposal. "
        }
      ]
    },
    "Description": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DescriptionString"
        },
        {
          "description": " The description of the proposal. "
        }
      ]
    },
    "ProposedByMemberId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ResourceIdString"
        },
        {
          "description": " The unique identifier of the member that created the proposal. "
        }
      ]
    },
    "ProposedByMemberName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/NetworkMemberNameString"
        },
        {
          "description": " The name of the member that created the proposal. "
        }
      ]
    },
    "Status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ProposalStatus"
        },
        {
          "description": "<p>The status of the proposal. Values are as follows:</p> <ul> <li> <p> <code>IN_PROGRESS</code> - The proposal is active and open for member voting.</p> </li> <li> <p> <code>APPROVED</code> - The proposal was approved with sufficient <code>YES</code> votes among members according to the <code>VotingPolicy</code> specified for the <code>Network</code>. The specified proposal actions are carried out.</p> </li> <li> <p> <code>REJECTED</code> - The proposal was rejected with insufficient <code>YES</code> votes among members according to the <code>VotingPolicy</code> specified for the <code>Network</code>. The specified <code>ProposalActions</code> aren't carried out.</p> </li> <li> <p> <code>EXPIRED</code> - Members didn't cast the number of votes required to determine the proposal outcome before the proposal expired. The specified <code>ProposalActions</code> aren't carried out.</p> </li> <li> <p> <code>ACTION_FAILED</code> - One or more of the specified <code>ProposalActions</code> in a proposal that was approved couldn't be completed because of an error.</p> </li> </ul>"
        }
      ]
    },
    "CreationDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Timestamp"
        },
        {
          "description": " The date and time that the proposal was created. "
        }
      ]
    },
    "ExpirationDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Timestamp"
        },
        {
          "description": " The date and time that the proposal expires. This is the <code>CreationDate</code> plus the <code>ProposalDurationInHours</code> that is specified in the <code>ProposalThresholdPolicy</code>. After this date and time, if members haven't cast enough votes to determine the outcome according to the voting policy, the proposal is <code>EXPIRED</code> and <code>Actions</code> aren't carried out. "
        }
      ]
    },
    "Arn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ArnString"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the proposal. For more information about ARNs and their format, see <a href=\"https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html\">Amazon Resource Names (ARNs)</a> in the <i>Amazon Web Services General Reference</i>."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-managed-blockchain/examples/amazon-managed-blockchain-proposal-summary-example.json
{
  "ProposalId": "abc12345",
  "Description": "Example resource description",
  "ProposedByMemberId": "abc12345",
  "ProposedByMemberName": "my-resource",
  "Status": "ACTIVE",
  "CreationDate": "example-value",
  "ExpirationDate": "example-value",
  "Arn": "arn:aws:service:us-east-1:123456789012:resource/id"
}
